-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZFQtsxcwTfGRJ3Cg
LHiaQuFSvb1LXNPAjBYjgk7mPV6gCgYIKoZIzj0DAQehRANCAASfkYDaVWZ5qHsG
AT/HqoomXV1s1XiDz9eRdZTTmAuLJXpry8GldYtHJCCq4TlhMH3PVL1ls4kNoDOS
TnRpMfLK
-----END PRIVATE KEY-----